"""Re-runs the liquidity-ranked universe study weekly and keeps a dated trend of the result.

`--universe-study` (README "Universe") was rejected once, on history up to 2026-09. Markets change:
this reruns it on whatever history is current and appends one row per interval to
`docs/research/universe-study-history.csv`, so a real regime shift shows up as a run of passing
weeks instead of requiring someone to remember to re-check. `docs/research/universe-study.md` is
overwritten each run with the full latest report plus the trend table. Adoption is still a human
decision: this never changes `config.yaml` itself, however the study comes out.

    python scripts/weekly_universe_study.py

Run from the repo root. Used by .github/workflows/universe-study.yml; safe to run locally too.
"""
import csv
import datetime as dt
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from hlg.backtest import DEF, universe_study  # noqa: E402
from hlg.common import load_config, setup_logging  # noqa: E402
HIST = ROOT / "docs" / "research" / "universe-study-history.csv"
REPORT = ROOT / "docs" / "research" / "universe-study.md"
FIELDS = ["date", "interval", "trades", "pf", "max_dd_pct", "oos_pf", "passed"]


def run():
    setup_logging()
    cfg = load_config(str(ROOT / "config.yaml")) if (ROOT / "config.yaml").exists() else {}
    P = {**DEF, **cfg.get("backtest", {})}
    today = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")

    HIST.parent.mkdir(parents=True, exist_ok=True)
    rows_out = []
    if HIST.exists():
        rows_out = list(csv.DictReader(HIST.open(encoding="utf-8")))

    sections = []
    for iv in ("1d", "4h"):
        rows, passed = universe_study(P, iv)
        cand = rows.get("auto_top30", {})
        rows_out.append({
            "date": today, "interval": iv, "trades": cand.get("trades", 0),
            "pf": round(cand.get("pf", 0) or 0, 2), "max_dd_pct": round(cand.get("max_dd_pct", 0) or 0, 2),
            "oos_pf": round(cand.get("OOS_pf", 0) or 0, 2), "passed": passed,
        })
        report_path = ROOT / "backtest_out" / f"universe_{iv}.md"
        if report_path.exists():
            sections.append(report_path.read_text(encoding="utf-8"))

    with HIST.open("w", encoding="utf-8", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        w.writerows(rows_out)

    trend = ["| date | interval | trades | PF | max DD | OOS PF | verdict |", "|---|---|---:|---:|---:|---:|---|"]
    for r in rows_out[-24:]:  # ~6 months at a weekly cadence
        trend.append(f"| {r['date']} | {r['interval']} | {r['trades']} | {r['pf']} | {r['max_dd_pct']}% | "
                      f"{r['oos_pf']} | {'PASS' if r['passed'] in (True, 'True') else 'fail'} |")

    doc = (
        "# Universe study: weekly trend\n\n"
        "Auto-generated by `.github/workflows/universe-study.yml` (`scripts/weekly_universe_study.py`). "
        "Re-runs `hlg.backtest --universe-study` (README \"Universe\") against current history, so a real "
        "shift toward the liquidity-ranked universe outperforming the fixed list shows up as a run of "
        "passing weeks here rather than requiring anyone to remember to re-check. **Never changes "
        "`config.yaml` itself** — adoption stays a human decision either way.\n\n"
        "## Trend (auto_top30 vs the adoption rule: PF >= 1.4, max DD >= fixed - 5pp, OOS PF > 1.2)\n\n"
        + "\n".join(trend) + "\n\n## Latest full report\n\n" + "\n\n---\n\n".join(sections)
    )
    REPORT.write_text(doc, encoding="utf-8")
    print(f"wrote {HIST} ({len(rows_out)} rows) and {REPORT}")


if __name__ == "__main__":
    run()
